In [1]:
import numpy as np
import pandas as pd

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)

# 1


def Print_First_3_Rows(df):
    return (df.head(3))

# 2


def delete_nan_values(df1):
    df.dropna(axis=0, inplace=True)
    return (df)

# 3


def Extract_Name_And_Score(df):
    return (df[["name", "score"]])

# 4


def add_New_Row_K(df):
    new_row = pd.Series({'name': "Suresh", "score": 15.5,
                         "attempts": 1, "qualify": "yes"})
    df.loc["k"] = new_row
    return (df)

# 5


def delete_attempts(df):
    df.drop("attempts", axis=1, inplace=True)
    return (df)

# 6


def add_new_col_Success(df):
    df['Success'] = df["score"].apply(lambda x: 1 if x > 10 else 0)
    return df


print(f"""\nCheckpoint 7 Answer Sheet\n
Given DataFrame\n
{df}\n
1.Print the three first rows using the head() method.\n
{Print_First_3_Rows(df)}\n
2.Delete rows with Nan values.\n
{delete_nan_values(df)}\n
3.Extract the 'name' and 'score' columns from the DataFrame.\n
{Extract_Name_And_Score(df)}\n
4.Write a Pandas program to append a new row 'k' to the DataFrame with these values (name: "Suresh", score: 15.5, attempts: 1, qualify: "yes").\n
{add_New_Row_K(df)}\n
5.Write a Pandas program to delete the 'attempts' column from the DataFrame.\n
{delete_attempts(df)}\n
6.Add a new column "Success": if the score is higher than 10 we will have 1, else we will have 0.\n
{add_new_col_Success(df)}\n
7.After executing the final DataFrame, export it into a CSV file named "my_data".\n
File is saved in the same directory!!
""")

# 7
df.to_csv('my_data.csv')

Checkpoint 7 Answer Sheet

Given DataFrame

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

1.Print the three first rows using the head() method.

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

2.Delete rows with Nan values.

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

3.Extract the 'name' and 'score' columns from the DataFrame.

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
i      Kevin    8.0
j      Jonas   19.0

4.Write a Pandas program to append a new row 'k' to the DataFrame with these values (name: "Suresh", score: 15.5, attempts: 1, qualify: "yes").

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

5.Write a Pandas program to delete the 'attempts' column from the DataFrame.

        name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
i      Kevin    8.0      no
j      Jonas   19.0     yes
k     Suresh   15.5     yes

6.Add a new column "Success": if the score is higher than 10 we will have 1, else we will have 0.

        name  score qualify  Success
a  Anastasia   12.5     yes        1
b       Dima    9.0      no        0
c  Katherine   16.5     yes        1
e      Emily    9.0      no        0
f    Michael   20.0     yes        1
g    Matthew   14.5     yes        1
i      Kevin    8.0      no        0
j      Jonas   19.0     yes        1
k     Suresh   15.5     yes        1

7.After executing the final DataFrame, export it into a CSV file named "my_data".

File is saved in the same directory!!